//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<refinedstorage:fluid_storage_part>);
recipes.remove(<refinedstorage:storage_part>);
recipes.remove(<refinedstorage:controller>);
recipes.remove(<refinedstorage:processor:2>);
recipes.remove(<refinedstorage:processor:1>);
recipes.remove(<refinedstorage:processor>);
recipes.remove(<refinedstorage:fluid_storage:4>);
recipes.remove(<techguns:simplemachine2:9>);
recipes.remove(<rftools:machine_frame>);
recipes.remove(<rftools:machine_base>);
recipes.remove(<techguns:simplemachine:10>);
recipes.remove(<techguns:simplemachine2:8>);
recipes.remove(<techguns:itemshared:65>);
recipes.remove(<immersiveintelligence:material_ingot:5>);
recipes.remove(<mekanism:controlcircuit:3>);
recipes.remove(<mekanism:controlcircuit:2>);
recipes.remove(<techguns:itemshared:66>);
recipes.remove(<hbm:dwarven_pickaxe>);
recipes.remove(<aquaculture:neptunium_leggings>);
recipes.remove(<aquaculture:neptunium_helmet>);
recipes.remove(<aquaculture:neptunium_boots>);
recipes.remove(<aquaculture:neptunium_chestplate>);
recipes.remove(<aquaculture:neptunium_sword>);
recipes.remove(<aquaculture:neptunium_hoe>);
recipes.remove(<aquaculture:neptunium_pickaxe>);
recipes.remove(<aquaculture:neptunium_shovel>);
recipes.remove(<aquaculture:neptunium_axe>);
recipes.remove(<immersiveengineering:material:2>);
recipes.remove(<immersiveengineering:material:1>);
recipes.remove(<hbm:cobalt_sword>);
recipes.remove(<hbm:cmb_sword>);
recipes.remove(<hbm:desh_sword>);
recipes.remove(<hbm:alloy_sword>);
recipes.remove(<hbm:cobalt_plate>);
recipes.remove(<hbm:cobalt_helmet>);
recipes.remove(<hbm:cobalt_legs>);
recipes.remove(<hbm:cobalt_boots>);
recipes.remove(<hbm:desh_pickaxe>);
recipes.remove(<hbm:alloy_axe>);
recipes.remove(<hbm:alloy_shovel>);
recipes.remove(<hbm:alloy_pickaxe>);
recipes.remove(<hbm:cobalt_hoe>);
recipes.remove(<hbm:alloy_hoe>);
recipes.remove(<hbm:desh_shovel>);
recipes.remove(<hbm:cmb_pickaxe>);
recipes.remove(<hbm:cobalt_shovel>);
recipes.remove(<hbm:cobalt_axe>);
recipes.remove(<hbm:cmb_axe>);
recipes.remove(<hbm:cmb_shovel>);
recipes.remove(<hbm:cmb_hoe>);
recipes.remove(<hbm:cobalt_pickaxe>);
recipes.remove(<hbm:desh_hoe>);
recipes.remove(<hbm:desh_axe>);
recipes.remove(<hbm:titanium_sword>);
recipes.remove(<hbm:steel_sword>);
recipes.remove(<hbm:steel_hoe>);
recipes.remove(<hbm:steel_shovel>);
recipes.remove(<hbm:steel_axe>);
recipes.remove(<hbm:steel_pickaxe>);
recipes.remove(<hbm:titanium_hoe>);
recipes.remove(<hbm:titanium_shovel>);
recipes.remove(<hbm:titanium_axe>);
recipes.remove(<hbm:titanium_pickaxe>);
recipes.remove(<mekanismtools:obsidianboots>);
recipes.remove(<mekanismtools:obsidianleggings>);
recipes.remove(<mekanismtools:obsidianhelmet>);
recipes.remove(<mekanismtools:obsidianchestplate>);
recipes.remove(<mekanismtools:obsidiansword>);
recipes.remove(<mekanismtools:obsidianpickaxe>);
recipes.remove(<mekanismtools:obsidianaxe>);
recipes.remove(<mekanismtools:obsidianshovel>);
recipes.remove(<mekanismtools:obsidianhoe>);
recipes.remove(<mekanismtools:bronzeleggings>);
recipes.remove(<mekanismtools:bronzeboots>);
recipes.remove(<mekanismtools:glowstonechestplate>);
recipes.remove(<mekanismtools:bronzechestplate>);
recipes.remove(<mekanismtools:glowstonesword>);
recipes.remove(<mekanismtools:bronzehoe>);
recipes.remove(<mekanismtools:bronzeaxe>);
recipes.remove(<mekanismtools:glowstoneaxe>);
recipes.remove(<mekanismtools:glowstonepickaxe>);
recipes.remove(<mekanismtools:bronzepaxel>);
recipes.remove(<mekanismtools:bronzeshovel>);
recipes.remove(<mekanismtools:glowstoneboots>);
recipes.remove(<mekanismtools:glowstonehelmet>);
recipes.remove(<mekanismtools:goldpaxel>);
recipes.remove(<mekanismtools:ironpaxel>);
recipes.remove(<mekanismtools:bronzepickaxe>);
recipes.remove(<mekanismtools:glowstonehoe>);
recipes.remove(<mekanismtools:glowstoneleggings>);
recipes.remove(<mekanismtools:bronzesword>);
recipes.remove(<mekanismtools:bronzehelmet>);
recipes.remove(<mekanismtools:woodpaxel>);
recipes.remove(<mekanismtools:stonepaxel>);
recipes.remove(<mekanismtools:diamondpaxel>);
recipes.remove(<mekanismtools:glowstoneshovel>);
recipes.remove(<mekanismtools:glowstonepaxel>);
recipes.remove(<mekanismtools:steelaxe>);
recipes.remove(<mekanismtools:osmiumaxe>);
recipes.remove(<mekanismtools:osmiumsword>);
recipes.remove(<mekanismtools:steelshovel>);
recipes.remove(<mekanismtools:lapislazulihoe>);
recipes.remove(<mekanismtools:steelsword>);
recipes.remove(<mekanismtools:steelpaxel>);
recipes.remove(<mekanismtools:lapislazulisword>);
recipes.remove(<mekanismtools:osmiumhelmet>);
recipes.remove(<mekanismtools:lapislazuliboots>);
recipes.remove(<mekanismtools:lapislazulileggings>);
recipes.remove(<mekanismtools:lapislazulichestplate>);
recipes.remove(<mekanismtools:steelpickaxe>);
recipes.remove(<mekanismtools:osmiumboots>);
recipes.remove(<mekanismtools:osmiumhoe>);
recipes.remove(<mekanismtools:osmiumpaxel>);
recipes.remove(<mekanismtools:lapislazulihelmet>);
recipes.remove(<mekanismtools:steelboots>);
recipes.remove(<mekanismtools:osmiumchestplate>);
recipes.remove(<mekanismtools:osmiumleggings>);
recipes.remove(<mekanismtools:lapislazulishovel>);
recipes.remove(<mekanismtools:lapislazulipickaxe>);
recipes.remove(<mekanismtools:steelhoe>);
recipes.remove(<mekanismtools:steelleggings>);
recipes.remove(<mekanismtools:steelhelmet>);
recipes.remove(<mekanismtools:lapislazuliaxe>);
recipes.remove(<mekanismtools:lapislazulipaxel>);
recipes.remove(<mekanismtools:osmiumpickaxe>);
recipes.remove(<mekanismtools:osmiumshovel>);
recipes.remove(<hbm:alloy_boots>);
recipes.remove(<hbm:alloy_legs>);
recipes.remove(<hbm:alloy_plate>);
recipes.remove(<hbm:alloy_helmet>);
recipes.remove(<hbm:titanium_boots>);
recipes.remove(<hbm:titanium_legs>);
recipes.remove(<hbm:titanium_plate>);
recipes.remove(<hbm:steel_plate>);
recipes.remove(<hbm:titanium_helmet>);
recipes.remove(<minecraft:diamond_boots>);
recipes.remove(<minecraft:diamond_leggings>);
recipes.remove(<minecraft:diamond_chestplate>);
recipes.remove(<minecraft:diamond_helmet>);
recipes.remove(<minecraft:golden_boots>);
recipes.remove(<minecraft:golden_leggings>);
recipes.remove(<minecraft:golden_chestplate>);
recipes.remove(<minecraft:golden_helmet>);
recipes.remove(<hbm:steel_boots>);
recipes.remove(<hbm:steel_legs>);
recipes.remove(<hbm:steel_plate>);
recipes.remove(<hbm:steel_helmet>);
recipes.remove(<minecraft:iron_boots>);
recipes.remove(<minecraft:iron_leggings>);
recipes.remove(<minecraft:iron_chestplate>);
recipes.remove(<minecraft:iron_helmet>);
recipes.remove(<industrialrenewal:fluid_tank>);
recipes.remove(<industrialrenewal:battery>);
recipes.remove(<refinedstorage:silicon>);
furnace.remove(<refinedstorage:silicon>);
recipes.remove(<mobinhibitor:mobinhibitor_passive>);
recipes.remove(<mobinhibitor:mobinhibitor_water>);
recipes.remove(<mobinhibitor:mobinhibitor_hostile>);
recipes.remove(<mcheli:krupp_c_34>);
recipes.remove(<mcheli:bnr32>);
recipes.remove(<gravitygun:gravitygun:1>);
recipes.remove(<gravitygun:gravitygun>);
recipes.remove(<portalgun:item_miniature_black_hole>);
recipes.remove(<mcheli:12.7>);
recipes.remove(<mcheli:15.5>);
recipes.remove(<mcheli:sea_sparrow>);
recipes.remove(<mcheli:searam>);
recipes.remove(<mcheli:bofors40mml60>);
recipes.remove(<mcheli:oto76mm>);
recipes.remove(<mcheli:mk15>);
recipes.remove(<mcheli:type93_launcher>);
recipes.remove(<mcheli:25mmaamg>);
recipes.remove(<mcheli:mk32>);
recipes.remove(<mcheli:vads>);
recipes.remove(<mcheli:s-75>);
recipes.remove(<mcheli:mim-23>);
recipes.remove(<mcheli:oto127mm>);
recipes.remove(<mcheli:12.7s>);
recipes.remove(<mcheli:merkava_mk4>);
recipes.remove(<mcheli:mxtmv>);
recipes.remove(<mcheli:kurganets25>);
recipes.remove(<mcheli:growler>);
recipes.remove(<mcheli:m1a2>);
recipes.remove(<mcheli:centauro>);
recipes.remove(<mcheli:t-90>);
recipes.remove(<mcheli:m1129>);
recipes.remove(<mcheli:kv-2>);
recipes.remove(<mcheli:t84>);
recipes.remove(<mcheli:m26>);
recipes.remove(<mcheli:su37>);
recipes.remove(<mcheli:f-35b>);
recipes.remove(<mcheli:harrier_en>);
recipes.remove(<mcheli:f-35a>);
recipes.remove(<mcheli:f-35c>);
recipes.remove(<mcheli:macchi_m33>);
recipes.remove(<mcheli:tornado-gr4>);
recipes.remove(<mcheli:us-2>);
recipes.remove(<mcheli:f-15e>);
recipes.remove(<mcheli:zodiac>);
recipes.remove(<mcheli:mq-9>);
recipes.remove(<mcheli:mig29>);
recipes.remove(<mcheli:md90>);
recipes.remove(<mcheli:n1k1>);
recipes.remove(<mcheli:x-47b>);
recipes.remove(<mcheli:p-51d>);
recipes.remove(<mcheli:f22a>);
recipes.remove(<mcheli:f14d>);
recipes.remove(<mcheli:mv-22>);
recipes.remove(<mcheli:skylark>);
recipes.remove(<mcheli:fa18f>);
recipes.remove(<mcheli:p180>);
recipes.remove(<mcheli:bqm_74e>);
recipes.remove(<mcheli:su-47>);
recipes.remove(<mcheli:f1m>);
recipes.remove(<mcheli:fi167>);
recipes.remove(<mcheli:stinger_390x>);
recipes.remove(<mcheli:harrier>);
recipes.remove(<mcheli:a6m2>);
recipes.remove(<mcheli:c5>);
recipes.remove(<mcheli:ac-130>);
recipes.remove(<mcheli:b29>);
recipes.remove(<mcheli:a-10>);
recipes.remove(<mcheli:robinson_r44f>);
recipes.remove(<mcheli:macchi_mc72>);
recipes.remove(<mcheli:mark5>);
recipes.remove(<mcheli:an2>);
recipes.remove(<mcheli:su-33>);
recipes.remove(<mcheli:e767>);
recipes.remove(<mcheli:t-4>);
recipes.remove(<mcheli:h8k>);
recipes.remove(<mcheli:f-15s_mtd>);
recipes.remove(<mcheli:emb314>);
recipes.remove(<mcheli:cb90>);
recipes.remove(<mcheli:b-2a>);
recipes.remove(<mcheli:project1204>);
recipes.remove(<mcheli:f4a>);
recipes.remove(<mcheli:mqm170>);
recipes.remove(<mcheli:tornado-ids>);
recipes.remove(<mcheli:cessna172>);
recipes.remove(<mcheli:rc-goblin-bomb>);
recipes.remove(<mcheli:bell47g>);
recipes.remove(<mcheli:ah-6>);
recipes.remove(<mcheli:bell47gf>);
recipes.remove(<mcheli:mh-6>);
recipes.remove(<mcheli:sh-60>);
recipes.remove(<mcheli:mh-60g>);
recipes.remove(<mcheli:ah-6x>);
recipes.remove(<mcheli:uh-1c>);
recipes.remove(<mcheli:mi-24>);
recipes.remove(<mcheli:mh-60l_dap>);
recipes.remove(<mcheli:ec665>);
recipes.remove(<mcheli:bell206l>);
recipes.remove(<mcheli:fl282>);
recipes.remove(<mcheli:nh90>);
recipes.remove(<mcheli:ah-64>);
recipes.remove(<mcheli:rc-goblin>);
recipes.remove(<mcheli:penetrator>);
recipes.remove(<mcheli:w3>);
recipes.remove(<mcheli:gltd>);
recipes.remove(<mcheli:mi28>);
recipes.remove(<mcheli:mi-24ps>);
recipes.remove(<mcheli:chain>);
recipes.remove(<mcheli:container>);
recipes.remove(<mcheli:mh-53e>);
recipes.remove(<mcheli:sh-3>);
recipes.remove(<mcheli:ka-29>);
recipes.remove(<mcheli:ka50n>);
recipes.remove(<mcheli:ka-27>);
recipes.remove(<mcheli:oh-1>);
recipes.remove(<mcheli:bell207>);
recipes.remove(<mcheli:ah-1z>);
recipes.remove(<mcheli:mq-8b>);
recipes.remove(<mcheli:ch47>);
recipes.remove(<mcheli:fgm148>);
recipes.remove(<mcheli:fim92>);
recipes.remove(<mcheli:fgm148_bullet>);
recipes.remove(<mcheli:fim92_bullet>);
recipes.remove(<mcheli:m18_green>);
recipes.remove(<mcheli:m18_violet>);
recipes.remove(<mcheli:m18_yellow>);
recipes.remove(<mcheli:m18_red>);
recipes.remove(<mcheli:ka52>);
recipes.remove(<mcheli:fuel>);
recipes.remove(<mcheli:uav_station2>);
recipes.remove(<mcheli:drafting_table>);
recipes.remove(<mcheli:uav_station>);
recipes.remove(<mcheli:spawn_gunner_vs_player>);
recipes.remove(<mcheli:spawn_gunner_vs_monster>);
//Don't touch me!
//#Add
recipes.addShaped(<refinedstorage:fluid_storage:4>, [[<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>],[<refinedstorage:quartz_enriched_iron>, <hbm:item_expensive:1>, <refinedstorage:quartz_enriched_iron>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<techguns:simplemachine:10>, [[<ore:plateSteel>, <hbm:circuit:8>, <ore:plateSteel>],[<hbm:coil_copper_torus>, <hbm:charger>, <hbm:coil_copper_torus>], [<ore:plateSteel>, <hbm:wire_fine:32>, <ore:plateSteel>]]);
recipes.addShaped(<hbm:cmb_axe>, [[<hbm:ingot_combine_steel>, <hbm:ingot_combine_steel>, null],[<hbm:ingot_combine_steel>, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cmb_shovel>, [[null, <hbm:ingot_combine_steel>, null],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cmb_hoe>, [[<hbm:ingot_combine_steel>, <hbm:ingot_combine_steel>, null],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cmb_pickaxe>, [[<hbm:ingot_combine_steel>, <hbm:ingot_combine_steel>, <hbm:ingot_combine_steel>],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cobalt_axe>, [[<hbm:ingot_cobalt>, <hbm:ingot_cobalt>, null],[<hbm:ingot_cobalt>, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cobalt_shovel>, [[null, <hbm:ingot_cobalt>, null],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cobalt_hoe>, [[<hbm:ingot_cobalt>, <hbm:ingot_cobalt>, null],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cobalt_pickaxe>, [[<hbm:ingot_cobalt>, <hbm:ingot_cobalt>, <hbm:ingot_cobalt>],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:desh_axe>, [[<hbm:ingot_desh>, <hbm:ingot_desh>, null],[<hbm:ingot_desh>, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:desh_shovel>, [[null, <hbm:ingot_desh>, null],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:desh_hoe>, [[<hbm:ingot_desh>, <hbm:ingot_desh>, null],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:desh_pickaxe>, [[<hbm:ingot_desh>, <hbm:ingot_desh>, <hbm:ingot_desh>],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:desh_sword>, [[null, <hbm:ingot_desh>, null],[null, <hbm:ingot_desh>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cmb_sword>, [[null, <hbm:ingot_combine_steel>, null],[null, <hbm:ingot_combine_steel>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<hbm:cobalt_sword>, [[null, <hbm:ingot_cobalt>, null],[null, <hbm:ingot_cobalt>, null], [null, <immersiveengineering:material:2>, null]]);
recipes.addShaped(<mekanismtools:obsidianboots>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_boots>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidianchestplate>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_chestplate>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidianleggings>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_leggings>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidianhelmet>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_helmet>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidiansword>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_sword>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidianpickaxe>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_pickaxe>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidianaxe>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_axe>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidianshovel>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_shovel>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<mekanismtools:obsidianhoe>, [[null, <mekanism:ingot>, null],[<mekanism:ingot>, <futuremc:netherite_hoe>, <mekanism:ingot>], [null, <mekanism:ingot>, null]]);
recipes.addShaped(<hbm:titanium_boots>, [[null, null, null],[<hbm:plate_titanium>, null, <hbm:plate_titanium>], [<hbm:plate_titanium>, <hbm:steel_boots>, <hbm:plate_titanium>]]);
recipes.addShaped(<hbm:titanium_legs>, [[<hbm:plate_titanium>, <hbm:plate_titanium>, <hbm:plate_titanium>],[<hbm:plate_titanium>, <hbm:steel_legs>, <hbm:plate_titanium>], [<hbm:plate_titanium>, null, <hbm:plate_titanium>]]);
recipes.addShaped(<hbm:titanium_plate>, [[<hbm:plate_titanium>, <hbm:plate_titanium>, <hbm:plate_titanium>],[<hbm:plate_titanium>, <hbm:steel_plate>, <hbm:plate_titanium>], [<hbm:plate_titanium>, <hbm:plate_titanium>, <hbm:plate_titanium>]]);
recipes.addShaped(<hbm:titanium_helmet>, [[<hbm:plate_titanium>, <hbm:plate_titanium>, <hbm:plate_titanium>],[<hbm:plate_titanium>, <hbm:steel_helmet>, <hbm:plate_titanium>], [null, null, null]]);
recipes.addShaped(<hbm:steel_boots>, [[null, null, null],[<hbm:plate_steel>, null, <hbm:plate_steel>], [<hbm:plate_steel>, <minecraft:leather_boots>, <hbm:plate_steel>]]);
recipes.addShaped(<hbm:steel_legs>, [[<hbm:plate_steel>, <hbm:plate_steel>, <hbm:plate_steel>],[<hbm:plate_steel>, <minecraft:leather_leggings>, <hbm:plate_steel>], [<hbm:plate_steel>, null, <hbm:plate_steel>]]);
recipes.addShaped(<hbm:steel_plate>, [[<hbm:plate_steel>, <hbm:plate_steel>, <hbm:plate_steel>],[<hbm:plate_steel>, <minecraft:leather_chestplate>, <hbm:plate_steel>], [<hbm:plate_steel>, <hbm:plate_steel>, <hbm:plate_steel>]]);
recipes.addShaped(<hbm:steel_helmet>, [[<hbm:plate_steel>, <hbm:plate_steel>, <hbm:plate_steel>],[<hbm:plate_steel>, <minecraft:leather_helmet>, <hbm:plate_steel>], [null, null, null]]);
recipes.addShaped(<minecraft:iron_boots>, [[null, null, null],[<hbm:plate_iron>, null, <hbm:plate_iron>], [<hbm:plate_iron>, <minecraft:leather_boots>, <hbm:plate_iron>]]);
recipes.addShaped(<minecraft:iron_leggings>, [[<hbm:plate_iron>, <hbm:plate_iron>, <hbm:plate_iron>],[<hbm:plate_iron>, <minecraft:leather_leggings>, <hbm:plate_iron>], [<hbm:plate_iron>, null, <hbm:plate_iron>]]);
recipes.addShaped(<minecraft:iron_chestplate>, [[<hbm:plate_iron>, <hbm:plate_iron>, <hbm:plate_iron>],[<hbm:plate_iron>, <minecraft:leather_chestplate>, <hbm:plate_iron>], [<hbm:plate_iron>, <hbm:plate_iron>, <hbm:plate_iron>]]);
recipes.addShaped(<minecraft:iron_helmet>, [[<hbm:plate_iron>, <hbm:plate_iron>, <hbm:plate_iron>],[<hbm:plate_iron>, <minecraft:leather_helmet>, <hbm:plate_iron>], [null, null, null]]);
recipes.addShaped(<industrialrenewal:fluid_tank>, [[<hbm:plate_cast:7400>, <hbm:machine_fluidtank>, <hbm:plate_cast:7400>],[<hbm:plate_cast:7400>, <hbm:machine_fluidtank>, <hbm:plate_cast:7400>], [<industrialrenewal:catwalk_pillar>, <industrialrenewal:fluid_gauge>, <industrialrenewal:catwalk_pillar>]]);
recipes.addShaped(<immersiveengineering:storage:8>, [[null, null, null],[null, <industrialrenewal:block_steel>, null], [null, null, null]]);
recipes.addShaped(<hbm:powder_aluminium>, [[null, null, null],[null, <immersiveengineering:metal:10>, null], [null, null, null]]);
recipes.addShaped(<industrialrenewal:battery_lithium>, [[<hbm:wire_fine:2900>, <hbm:lithium>, <hbm:wire_fine:2900>],[<hbm:ingot_cobalt>, <industrialrenewal:battery>, <hbm:ingot_cobalt>], [<hbm:ingot_cobalt>, <hbm:ingot_cobalt>, <hbm:ingot_cobalt>]]);
recipes.addShaped(<industrialrenewal:battery>, [[<hbm:wire_fine:2900>, <minecraft:redstone>, <hbm:wire_fine:2900>],[<hbm:wire_fine:2900>, <minecraft:redstone>, <hbm:wire_fine:2900>], [<hbm:ingot_lead>, <hbm:ingot_lead>, <hbm:ingot_lead>]]);
recipes.addShaped(<hbm:railing_end_floor>, [[null, null, null],[null, <hbm:railing_end_flipped_floor>, null], [null, null, null]]);
recipes.addShaped(<hbm:railing_end_flipped_floor>, [[null, null, null],[null, <hbm:railing_end_floor>, null], [null, null, null]]);
recipes.addShaped(<hbm:railing_end_flipped_floor>, [[null, null, null],[null, <hbm:railing_normal>, <hbm:steel_beam>], [null, null, null]]);
recipes.addShaped(<hbm:railing_end_flipped_self>, [[null, null, null],[null, <hbm:railing_end_self>, null], [null, null, null]]);
recipes.addShaped(<hbm:railing_end_self>, [[null, null, null],[null, <hbm:railing_end_flipped_self>, null], [null, null, null]]);
recipes.addShaped(<hbm:railing_end_flipped_self>, [[null, null, null],[null, <hbm:railing_normal>, null], [null, null, null]]);
recipes.addShaped(<hbm:railing_bend> * 3, [[null, <hbm:railing_normal>, <hbm:railing_normal>],[null, null, <hbm:railing_normal>], [null, null, null]]);
recipes.addShaped(<hbm:railing_normal> * 12, [[<hbm:steel_beam>, <hbm:steel_beam>, <hbm:steel_beam>],[null, <hbm:steel_beam>, null], [<hbm:steel_beam>, <hbm:steel_beam>, <hbm:steel_beam>]]);
recipes.addShaped(<hbm:ladder_red> * 8, [[<hbm:ladder_steel>, <hbm:ladder_steel>, <hbm:ladder_steel>],[<hbm:ladder_steel>, <minecraft:dye:1>, <hbm:ladder_steel>], [<hbm:ladder_steel>, <hbm:ladder_steel>, <hbm:ladder_steel>]]);
recipes.addShaped(<hbm:hazmat>, [[null, null, null],[<hbm:hazmat_cloth>, <hbm:hazmat_cloth>, null], [<hbm:hazmat_cloth>, <hbm:hazmat_cloth>, null]]);
recipes.addShaped(<hbm:bismuth_tool>, [[<hbm:nugget_bismuth>, <hbm:ingot_bismuth>, <hbm:nugget_bismuth>],[<hbm:nugget_bismuth>, <hbm:reacher>, <hbm:nugget_bismuth>], [<hbm:nugget_bismuth>, <hbm:magnetron>, <hbm:nugget_bismuth>]]);
recipes.addShaped(<hbm:watz_pellet:12>, [[null, <hbm:ingot_pu241>, null],[<hbm:ingot_pu241>, <hbm:ingot_graphite>, <hbm:ingot_pu241>], [null, <hbm:ingot_pu241>, null]]);
recipes.addShaped(<minecraft:paper> * 4, [[<minecraft:log:2>, <minecraft:log:2>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<portalstuff:light_bridge>, [[<hbm:crystal_schrabidium>, <hbm:plate_welded:36>, <hbm:item_expensive:4>],[<hbm:crystal_trixite>, <hbm:item_expensive:5>, <hbm:plate_welded:36>], [<hbm:crystal_schrabidium>, <hbm:plate_welded:36>, <hbm:item_expensive:4>]]);
recipes.addShaped(<portalstuff:fizzler> * 2, [[<hbm:wire_fine:12626>, <portalstuff:laser_fizzler>, <hbm:item_expensive:4>],[<hbm:wire_fine:12626>, <portalstuff:laser_fizzler>, <hbm:item_expensive:4>], [<hbm:wire_fine:12626>, <portalstuff:laser_fizzler>, <hbm:item_expensive:4>]]);
recipes.addShaped(<portalstuff:laser_fizzler> * 8, [[<hbm:undefined>, <hbm:plate_cast:36>, <hbm:item_expensive:6>],[<hbm:undefined>, <hbm:plate_welded:36>, <hbm:item_expensive:6>], [<hbm:undefined>, <hbm:plate_cast:36>, <hbm:item_expensive:6>]]);
recipes.addShaped(<portalstuff:floor_button_base>, [[null, null, null],[<hbm:plate_welded:2200>, <hbm:plate_cast:42>, <hbm:plate_welded:2200>], [<mekanism:reinforcedalloy>, <hbm:machine_schrabidium_battery>, <mekanism:reinforcedalloy>]]);
recipes.addShaped(<portalstuff:portal_placer> * 4, [[<hbm:bolt:33>, <hbm:wire_fine:12626>, <hbm:bolt:33>],[<hbm:bolt:33>, <hbm:wire_fine:12626>, <hbm:bolt:33>], [<hbm:bolt:33>, <hbm:telepad>, <hbm:bolt:33>]]);
recipes.addShaped(<hbm:telepad>, [[<hbm:plate_cast:39>, <hbm:glass_lead>, <hbm:plate_cast:39>],[<hbm:plate_cast:36>, <portalgun:item_miniature_black_hole>, <hbm:plate_cast:36>], [<hbm:wire_fine:38>, <hbm:plate_welded:36>, <hbm:wire_fine:38>]]);
recipes.addShaped(<portalstuff:companion_cube>, [[null, <bhc:red_heart>, null],[<bhc:green_heart>, <portalstuff:weighted_cube>, <bhc:blue_heart>], [null, <bhc:yellow_heart>, null]]);
recipes.addShaped(<portalstuff:smart_wire> * 8, [[null, <mekanism:reinforcedalloy>, null],[<mekanism:reinforcedalloy>, <minecraft:redstone_torch>, <mekanism:reinforcedalloy>], [null, <mekanism:reinforcedalloy>, null]]);
recipes.addShaped(<portalstuff:laser_emitter>, [[null, <hbm:shell:30>, <hbm:item_expensive:1>],[<hbm:part_barrel_heavy:30>, <hbm:laser_crystal_co2>, <hbm:wire_dense:7400>], [null, <hbm:shell:30>, <hbm:item_expensive:1>]]);
recipes.addShaped(<portalstuff:reflection_cube>, [[<hbm:plate_welded:2200>, <hbm:glass_quartz>, <hbm:plate_welded:2200>],[<hbm:glass_quartz>, <hbm:sphere_steel>, <hbm:glass_quartz>], [<hbm:plate_welded:2200>, <hbm:glass_quartz>, <hbm:plate_welded:2200>]]);
recipes.addShaped(<portalstuff:weighted_cube>, [[<hbm:plate_welded:2200>, <hbm:item_expensive>, <hbm:plate_welded:2200>],[<hbm:item_expensive>, <hbm:sphere_steel>, <hbm:item_expensive>], [<hbm:plate_welded:2200>, <hbm:item_expensive>, <hbm:plate_welded:2200>]]);
recipes.addShaped(<gravitygun:gravitygun:1>, [[null, <hbm:crystal_xen>, null],[null, <gravitygun:gravitygun>, null], [null, <hbm:machine_transformer_20>, null]]);
recipes.addShaped(<gravitygun:gravitygun>, [[<hbm:bolt:30>, <hbm:bolt:30>, null],[<hbm:bolt:30>, <hbm:crystal_xen>, <hbm:part_receiver_heavy:50>], [null, <hbm:part_receiver_light:30>, <hbm:part_grip:50>]]);
recipes.addShaped(<portalgun:item_miniature_black_hole>, [[null, <minecraft:glowstone_dust>, null],[<minecraft:glowstone_dust>, <hbm:crystal_xen>, <minecraft:glowstone_dust>], [null, <minecraft:glowstone_dust>, null]]);
recipes.addShaped(<mcheli:zodiac>, [[null, null, <hbm:pipe:20003>],[<hbm:ingot_rubber>, null, <hbm:motor>], [<hbm:ingot_rubber>, <hbm:ingot_rubber>, <hbm:ingot_rubber>]]);
recipes.addShaped(<mcheli:stinger_390x>, [[null, <hbm:pipe:30>, null],[<hbm:block_steel>, <hbm:circuit:8>, <hbm:plate_welded:30>], [<hbm:plate_cast:30>, <hbm:shell:50>, <hbm:plate_cast:30>]]);
recipes.addShaped(<mcheli:fgm148>, [[null, null, null],[null, <hbm:gun_missile_launcher>, null], [null, null, null]]);
recipes.addShaped(<mcheli:fim92>, [[null, null, null],[null, <hbm:gun_stinger>, null], [null, null, null]]);
recipes.addShaped(<mcheli:fgm148_bullet>, [[null, null, null],[null, <hbm:ammo_standard:58>, null], [null, null, null]]);
recipes.addShaped(<mcheli:fim92_bullet>, [[null, null, null],[null, <hbm:ammo_standard:59>, null], [null, null, null]]);
recipes.addShaped(<mcheli:fuel>, [[null, null, null],[null, <hbm:canister_fuel:20>, null], [null, null, null]]);
//File End
